# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8499e8a7424c0381822ae5e6c1ad13d085677b15f1fcbda79ff4372b81234a3a078595ea5687fae3079d3bb19ba610ccf71c02128efbcf44f9dda9757b2ae78e

test:
  secret_key_base: 8057afe944eb6c83158b24c97fd7527aa18afee99fe79f19054ce972b0149e52e4bddb98e445d1e5f12d2e7bbf1e07ac34fc086ca534c9995d376dbb7833f4b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
